### ISSUE TITLE
Lower Timeout

### ISSUE THREAD

**Issue by frumania** [aws-samples/aws-lambda-sap-odp-extractor#3]
Can you kindly lower the default lambda timeout to e.g. 1 min? Especially when dealing with Lambda private connectivity and related troubleshooting the turnaround times are high (especially for beginners it would simplify it).

timeout: cdk.Duration.seconds(300) -> timeout: cdk.Duration.seconds(60)

**Comment by kumarrk21** [comment]
I am leaving it as is to support broader use cases. Once you clone the repo, you can do either of these two

1) Implement a quicker timeout in the extractor.py where the requests library is used to issue a 'ge't command (line no. 195) - https://requests.readthedocs.io/en/master/user/quickstart/

2) Change it the lib/aws-sap-odp-stack.js  file.
