### ISSUE TITLE
Create Multiple Lambda functions

### ISSUE THREAD

**Issue by akashgupta22** [aws-samples/aws-lambda-sap-odp-extractor#5]
I have several SAP ODP data sources that I would need to extract. And I want to schedule the Lambda job for doing that for every data source. But this package produces ONE extractor and Lambda function, which is difficult to schedule in production with multiple data source. 

Can I create multiple Lambda functions with the extractors with different settings? If yes, then how? If no, is there a way to dynamically input the function parameters while scheduling?\

Please help. Thank you.

**Comment by kumarrk21** [comment]
Yes. In this sample code, the OData service settings are obtained from Lambda environment variables. If you want to use multiple ODP data sources, you can store those in a DynamoDB table and then use a Lambda function to fetch those entries and call other Lambdas asynchronously.

**Comment by akashgupta22** [comment]
Hi @kumarrk21 Thank you for your previous response. We are facing another issue.

We have **multiple ODP data sources in SAP** with same parameters (**Entity name, Service name, Host and Port**) Even the **Username is same**. **Only difference is the Password**. The password in the SAP system differentiates the Login to the respective Clients. 

But when I am implementing this in AWS Lambda, the system is working for one client, but as I am changing the password to connect to the other client keeping all other parameters same, it is failing to connect.

Is there any way I can tell my Lambda **how to differentiate different client sources with same parameters and different password**?

![AWS SAP fail screen](https://user-images.githubusercontent.com/52201113/96718955-c2311f80-1376-11eb-9017-e8f230275c3b.jpg)
