### ISSUE TITLE
Connect to Multiple ODATA clients with same parameters but different password

### ISSUE THREAD

**Issue by akashgupta22** [aws-samples/aws-lambda-sap-odp-extractor#6]
@kumarrk21 We have multiple ODP data sources in SAP with same parameters (Entity name, Service name, Host and Port) Even the Username is same. Only difference is the Password. The password in the SAP system differentiates the Login to the respective Clients.

But when I am implementing this in AWS Lambda, the system is working for one client, but as I am changing the password to connect to the other client keeping all other parameters same, it is failing to connect.
![AWS SAP fail screen](https://user-images.githubusercontent.com/52201113/96722735-b431cd80-137b-11eb-8991-236acd366ae1.jpg)

Is there any way I can tell my Lambda **how to differentiate different client sources with same parameters and different password**?

**Comment by kumarrk21** [comment]
You should pass the client number using sap-client url parameter. I suggest you review OData SAP doc for more details about this

**Comment by akashgupta22** [comment]
@kumarrk21 In the SAP ODP documentation in the link: [https://help.sap.com/doc/saphelp_me150/15.0.3VERSIONFORSAPME/en-US/54/5aff512ec09b33e10000000a44538d/content.htm?no_cache=true](url), I have not found anything related to SAP Client-URL parameter.

Actually our Host, port and Usernames are same for multiple clients. But the password keeps changing. Which the Extractor can't reach out.

**Comment by kumarrk21** [comment]
So, this sample extractor uses ODP as the data provider layer and then OData as the API access layer. You are trying to logon to the target SAP system using OData URL. For you to access the SAP system, you need to give the endpoint URL, and Authentication details (which you are providing). If you want to log on to specific client within an SAP instance, you should be supplying the sap-client url parameter in the url. You will need to update the python code accordingly.
