### ISSUE TITLE
Issues while extracting the data from SAP

### ISSUE THREAD

**Issue by akashgupta22** [aws-samples/aws-lambda-sap-odp-extractor#8]
Hi @kumarrk21 ,

We are trying to pull data with more than 8 million records in SAP. **SAP chunks this data available in several parts of ~50k size each**. The ODATA extractor is connecting with the service, pulling the Data, **but it is extracting only 1st part (~50k)** and **does not extract the rest of the 39 parts** with 50k records.

Is there anything in the code that we can modify to release this restriction? **How can we extract all the parts** and the entire data from SAP without facing this issue?

It will be great help if you could kindly reply. Thank you.

**Comment by kumarrk21** [comment]
Hi Akash - This should work based on the skip tokens. I see you have reached out through our account team for subsequent. An SA from the team should connect with you soon and can dig deep in to this with you. I am closing this issue and our team can connect offline. Works?

**Comment by akashgupta22** [comment]
@kumarrk21 Yes that works. My email: agupt.cg.asc@aldogroup.com. Contact no. - +1(438) 728-7578.
Please let me know how do I connect to the SA? I have the option to connect technical support from our AWS console. But the agent is assigned randomly and might not have knowledge about this issue. Please help se sort this out as we are planning to put this in prod. Thank you.
